In [ ]:
import numpy as np

# Create a 2D array (4x6 matrix)
arr_2d = np.array([
    [1,  2,  3,  4,  5,  6],
    [7,  8,  9,  10, 11, 12],
    [13, 14, 15, 16, 17, 18],
    [19, 20, 21, 22, 23, 24]
])

print(arr_2d)
print(f"Shape: {arr_2d.shape}")

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
Shape: (4, 6)


In [7]:
# 1. BASIC INDEXING - 2D Arrays

print("\n1.1 Access single element [row, col]:")
print(f"arr_2d[0, 0] = {arr_2d[0, 0]}")  # First element
print(f"arr_2d[0, 0] = {arr_2d[1, 1]}")  # First element

print(f"arr_2d[2, 3] = {arr_2d[2, 3]}")  # Middle element
print(f"arr_2d[-1, -1] = {arr_2d[-1, -1]}")  # Last element
print(f"arr_2d[-2, -3] = {arr_2d[-2, -3]}")  # Negative indexing


1.1 Access single element [row, col]:
arr_2d[0, 0] = 1
arr_2d[0, 0] = 8
arr_2d[2, 3] = 16
arr_2d[-1, -1] = 24
arr_2d[-2, -3] = 16


In [8]:

# 2. ROW SLICING - 2D Arrays

print("\n2.1 Select entire rows:")
print("arr_2d[0] - First row:")
print(arr_2d[0])

print("\narr_2d[2] - Third row:")
print(arr_2d[2])

print("\narr_2d[-1] - Last row:")
print(arr_2d[-1])

print("\n2.2 Select multiple consecutive rows:")
print("arr_2d[1:4] - Rows 1 to 3:")
print(arr_2d[1:4])

print("\narr_2d[:3] - First 3 rows:")
print(arr_2d[:3])

print("\narr_2d[2:] - From row 2 to end:")
print(arr_2d[2:])

print("\n2.3 Select rows with step:")
print("arr_2d[::2] - Every 2nd row:")
print(arr_2d[::2])

print("\narr_2d[1::2] - Every 2nd row starting from index 1:")
print(arr_2d[1::2])

print("\narr_2d[::-1] - Reverse all rows:")
print(arr_2d[::-1])



2.1 Select entire rows:
arr_2d[0] - First row:
[1 2 3 4 5 6]

arr_2d[2] - Third row:
[13 14 15 16 17 18]

arr_2d[-1] - Last row:
[19 20 21 22 23 24]

2.2 Select multiple consecutive rows:
arr_2d[1:4] - Rows 1 to 3:
[[ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]

arr_2d[:3] - First 3 rows:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]

arr_2d[2:] - From row 2 to end:
[[13 14 15 16 17 18]
 [19 20 21 22 23 24]]

2.3 Select rows with step:
arr_2d[::2] - Every 2nd row:
[[ 1  2  3  4  5  6]
 [13 14 15 16 17 18]]

arr_2d[1::2] - Every 2nd row starting from index 1:
[[ 7  8  9 10 11 12]
 [19 20 21 22 23 24]]

arr_2d[::-1] - Reverse all rows:
[[19 20 21 22 23 24]
 [13 14 15 16 17 18]
 [ 7  8  9 10 11 12]
 [ 1  2  3  4  5  6]]


In [9]:
# 3. COLUMN SLICING - 2D Arrays

print("\n3.1 Select entire columns:")
print("arr_2d[:, 0] - First column:")
print(arr_2d[:, 0])

print("\narr_2d[:, -1] - Last column:")
print(arr_2d[:, -1])

print("\n3.2 Select multiple consecutive columns:")
print("arr_2d[:, 1:4] - Columns 1 to 3:")
print(arr_2d[:, 1:4])

print("\narr_2d[:, :3] - First 3 columns:")
print(arr_2d[:, :3])

print("\narr_2d[:, 3:] - From column 3 to end:")
print(arr_2d[:, 3:])

print("\n3.3 Select columns with step:")
print("arr_2d[:, ::2] - Every 2nd column:")
print(arr_2d[:, ::2])

print("\narr_2d[:, ::-1] - Reverse all columns:")
print(arr_2d[:, ::-1])


3.1 Select entire columns:
arr_2d[:, 0] - First column:
[ 1  7 13 19]

arr_2d[:, -1] - Last column:
[ 6 12 18 24]

3.2 Select multiple consecutive columns:
arr_2d[:, 1:4] - Columns 1 to 3:
[[ 2  3  4]
 [ 8  9 10]
 [14 15 16]
 [20 21 22]]

arr_2d[:, :3] - First 3 columns:
[[ 1  2  3]
 [ 7  8  9]
 [13 14 15]
 [19 20 21]]

arr_2d[:, 3:] - From column 3 to end:
[[ 4  5  6]
 [10 11 12]
 [16 17 18]
 [22 23 24]]

3.3 Select columns with step:
arr_2d[:, ::2] - Every 2nd column:
[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]
 [19 21 23]]

arr_2d[:, ::-1] - Reverse all columns:
[[ 6  5  4  3  2  1]
 [12 11 10  9  8  7]
 [18 17 16 15 14 13]
 [24 23 22 21 20 19]]


In [12]:
# 4. COMBINED ROW & COLUMN SLICING - 2D Arrays
print(arr_2d)

print("\n4.1 Rectangular sub-arrays:")
print("arr_2d[1:4, 2:5] - Rows 1-3, Columns 2-4:")
print(arr_2d[1:4, 2:5])

print("\narr_2d[:3, :3] - Top-left 3x3 block:")
print(arr_2d[:3, :3])

print("\narr_2d[2:, 3:] - Bottom-right sub-array:")
print(arr_2d[2:, 3:])

print("\n4.2 With steps:")
print("arr_2d[::2, ::2] - Every 2nd row and column:")
print(arr_2d[::2, ::2])

print("\narr_2d[1::2, 1::2] - Alternate checkerboard pattern:")
print(arr_2d[1::2, 1::2])

print("\narr_2d[::-1, ::-1] - Complete reverse:")
print(arr_2d[::-1, ::-1])

# ----------------------------------------------------------------------------
# 5. ADVANCED INDEXING - 2D Arrays
# ----------------------------------------------------------------------------

print("\n" + "-" * 80)
print("5. ADVANCED INDEXING (Boolean & Fancy)")
print("-" * 80)

print("\n5.1 Boolean indexing:")
print("arr_2d > 15 - Elements greater than 15:")
print(arr_2d[arr_2d > 15])

print("\narr_2d[(arr_2d >= 10) & (arr_2d <= 20)] - Elements between 10 and 20:")
print(arr_2d[(arr_2d >= 10) & (arr_2d <= 20)])

print("\n5.2 Fancy indexing (specific rows):")
print("arr_2d[[0, 2, 4]] - Rows 0, 2, and 4:")
print(arr_2d[[0, 2, 3]])

print("\narr_2d[[1, 3], :] - Rows 1 and 3, all columns:")
print(arr_2d[[1, 3], :])

print("\n5.3 Fancy indexing (specific elements):")
rows = [0, 1, 2, 3]
cols = [0, 2, 4, 5]
print(f"arr_2d[{rows}, {cols}] - Diagonal-like elements:")
print(arr_2d[rows, cols])

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]

4.1 Rectangular sub-arrays:
arr_2d[1:4, 2:5] - Rows 1-3, Columns 2-4:
[[ 9 10 11]
 [15 16 17]
 [21 22 23]]

arr_2d[:3, :3] - Top-left 3x3 block:
[[ 1  2  3]
 [ 7  8  9]
 [13 14 15]]

arr_2d[2:, 3:] - Bottom-right sub-array:
[[16 17 18]
 [22 23 24]]

4.2 With steps:
arr_2d[::2, ::2] - Every 2nd row and column:
[[ 1  3  5]
 [13 15 17]]

arr_2d[1::2, 1::2] - Alternate checkerboard pattern:
[[ 8 10 12]
 [20 22 24]]

arr_2d[::-1, ::-1] - Complete reverse:
[[24 23 22 21 20 19]
 [18 17 16 15 14 13]
 [12 11 10  9  8  7]
 [ 6  5  4  3  2  1]]

--------------------------------------------------------------------------------
5. ADVANCED INDEXING (Boolean & Fancy)
--------------------------------------------------------------------------------

5.1 Boolean indexing:
arr_2d > 15 - Elements greater than 15:
[16 17 18 19 20 21 22 23 24]

arr_2d[(arr_2d >= 10) & (arr_2d <= 20)] - Elements between 10 and 20:
[10 11 12

In [4]:
# Create a 3D array (4x3x5 tensor)
arr_3d = np.arange(1, 61).reshape(4, 3, 5)

print("\n📊 Original 3D Array (4x3x5):")
print("Think of this as: 4 matrices, each 3 rows x 5 columns")
print(arr_3d)
print(f"Shape: {arr_3d.shape}")

print("\n3D Array visualization by matrix:")
for i in range(arr_3d.shape[0]):
    print(f"\nMatrix {i}:")
    print(arr_3d[i])


📊 Original 3D Array (4x3x5):
Think of this as: 4 matrices, each 3 rows x 5 columns
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]

 [[16 17 18 19 20]
  [21 22 23 24 25]
  [26 27 28 29 30]]

 [[31 32 33 34 35]
  [36 37 38 39 40]
  [41 42 43 44 45]]

 [[46 47 48 49 50]
  [51 52 53 54 55]
  [56 57 58 59 60]]]
Shape: (4, 3, 5)

3D Array visualization by matrix:

Matrix 0:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

Matrix 1:
[[16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]

Matrix 2:
[[31 32 33 34 35]
 [36 37 38 39 40]
 [41 42 43 44 45]]

Matrix 3:
[[46 47 48 49 50]
 [51 52 53 54 55]
 [56 57 58 59 60]]


In [5]:
# 6. BASIC INDEXING - 3D Arrays

print(arr_3d)

print("\n6.1 Access single element [matrix, row, col]:")
print(f"arr_3d[0, 0, 0] = {arr_3d[0, 0, 0]}")  # First element
print(f"arr_3d[1, 2, 3] = {arr_3d[1, 2, 3]}")  # Middle element
print(f"arr_3d[-1, -1, -1] = {arr_3d[-1, -1, -1]}")  # Last element

print("\n6.2 Access entire 2D matrices:")
print("arr_3d[0] - First matrix (3x5):")
print(arr_3d[0])

print("\narr_3d[-1] - Last matrix:")
print(arr_3d[-1])

print("\n6.3 Access rows from specific matrix:")
print("arr_3d[1, 0] - First row of 2nd matrix:")
print(arr_3d[1, 0])

print("\narr_3d[2, :, 2] - Column 2 from all rows in 3rd matrix:")
print(arr_3d[2, :, 2])

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]

 [[16 17 18 19 20]
  [21 22 23 24 25]
  [26 27 28 29 30]]

 [[31 32 33 34 35]
  [36 37 38 39 40]
  [41 42 43 44 45]]

 [[46 47 48 49 50]
  [51 52 53 54 55]
  [56 57 58 59 60]]]

6.1 Access single element [matrix, row, col]:
arr_3d[0, 0, 0] = 1
arr_3d[1, 2, 3] = 29
arr_3d[-1, -1, -1] = 60

6.2 Access entire 2D matrices:
arr_3d[0] - First matrix (3x5):
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

arr_3d[-1] - Last matrix:
[[46 47 48 49 50]
 [51 52 53 54 55]
 [56 57 58 59 60]]

6.3 Access rows from specific matrix:
arr_3d[1, 0] - First row of 2nd matrix:
[16 17 18 19 20]

arr_3d[2, :, 2] - Column 2 from all rows in 3rd matrix:
[33 38 43]


In [ ]:
# 7. MATRIX SLICING (DEPTH) - 3D Arrays
print(arr_3d)

print("\n7.1 Select multiple matrices:")
print("arr_3d[:2] - First 2 matrices:")
print(arr_3d[:2])

print("\narr_3d[1:3] - Matrices 1 and 2:")
print(arr_3d[1:3])

print("\narr_3d[::2] - Every 2nd matrix:")
print(arr_3d[::2])

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]

 [[16 17 18 19 20]
  [21 22 23 24 25]
  [26 27 28 29 30]]

 [[31 32 33 34 35]
  [36 37 38 39 40]
  [41 42 43 44 45]]

 [[46 47 48 49 50]
  [51 52 53 54 55]
  [56 57 58 59 60]]]

7.1 Select multiple matrices:
arr_3d[:2] - First 2 matrices:
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]

 [[16 17 18 19 20]
  [21 22 23 24 25]
  [26 27 28 29 30]]]

arr_3d[1:3] - Matrices 1 and 2:
[[[16 17 18 19 20]
  [21 22 23 24 25]
  [26 27 28 29 30]]

 [[31 32 33 34 35]
  [36 37 38 39 40]
  [41 42 43 44 45]]]

arr_3d[::2] - Every 2nd matrix:
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]

 [[31 32 33 34 35]
  [36 37 38 39 40]
  [41 42 43 44 45]]]


In [7]:
# 8. ROW SLICING IN 3D

print(arr_3d)

print("\n8.1 Rows from all matrices:")
print("arr_3d[:, 0, :] - First row from all matrices:")
print(arr_3d[:, 0, :])

print("\narr_3d[:, 1:, :] - Rows 1-2 from all matrices:")
print(arr_3d[:, 1:, :])

print("\n8.2 Rows from specific matrices:")
print("arr_3d[1:3, :2, :] - First 2 rows from matrices 1-2:")
print(arr_3d[1:3, :2, :])

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]

 [[16 17 18 19 20]
  [21 22 23 24 25]
  [26 27 28 29 30]]

 [[31 32 33 34 35]
  [36 37 38 39 40]
  [41 42 43 44 45]]

 [[46 47 48 49 50]
  [51 52 53 54 55]
  [56 57 58 59 60]]]

8.1 Rows from all matrices:
arr_3d[:, 0, :] - First row from all matrices:
[[ 1  2  3  4  5]
 [16 17 18 19 20]
 [31 32 33 34 35]
 [46 47 48 49 50]]

arr_3d[:, 1:, :] - Rows 1-2 from all matrices:
[[[ 6  7  8  9 10]
  [11 12 13 14 15]]

 [[21 22 23 24 25]
  [26 27 28 29 30]]

 [[36 37 38 39 40]
  [41 42 43 44 45]]

 [[51 52 53 54 55]
  [56 57 58 59 60]]]

8.2 Rows from specific matrices:
arr_3d[1:3, :2, :] - First 2 rows from matrices 1-2:
[[[16 17 18 19 20]
  [21 22 23 24 25]]

 [[31 32 33 34 35]
  [36 37 38 39 40]]]


In [13]:

# 9. COLUMN SLICING IN 3D

print(arr_3d)
print(arr_3d.shape)
print("\n9.1 Columns from all matrices:")
print("arr_3d[:, :, 0] - First column from all matrices:")
print(arr_3d[:, :, 0])

print("\narr_3d[:, :, 2:4] - Columns 2-3 from all matrices:")
print(arr_3d[:, :, 2:4])

# print("\n9.2 Columns with steps:")
# print("arr_3d[:, :, ::2] - Every 2nd column from all matrices:")
# print(arr_3d[:, :, ::2])

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]

 [[16 17 18 19 20]
  [21 22 23 24 25]
  [26 27 28 29 30]]

 [[31 32 33 34 35]
  [36 37 38 39 40]
  [41 42 43 44 45]]

 [[46 47 48 49 50]
  [51 52 53 54 55]
  [56 57 58 59 60]]]
(4, 3, 5)

9.1 Columns from all matrices:
arr_3d[:, :, 0] - First column from all matrices:
[[ 1  6 11]
 [16 21 26]
 [31 36 41]
 [46 51 56]]

arr_3d[:, :, 2:4] - Columns 2-3 from all matrices:
[[[ 3  4]
  [ 8  9]
  [13 14]]

 [[18 19]
  [23 24]
  [28 29]]

 [[33 34]
  [38 39]
  [43 44]]

 [[48 49]
  [53 54]
  [58 59]]]


In [9]:

# 10. COMBINED 3D SLICING

print(arr_3d)


print("\n10.1 Complex sub-arrays:")
print("arr_3d[1:3, 1:, 2:4] - Matrices 1-2, Rows 1-2, Columns 2-3:")
print(arr_3d[1:3, 1:, 2:4])

print("\narr_3d[:2, :2, :3] - Top-left-front cube:")
print(arr_3d[:2, :2, :3])

print("\n10.2 With steps in all dimensions:")
print("arr_3d[::2, ::2, ::2] - Every 2nd element in all dimensions:")
print(arr_3d[::2, ::2, ::2])

print("\narr_3d[::-1, ::-1, ::-1] - Complete 3D reverse:")
print(arr_3d[::-1, ::-1, ::-1])


[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]

 [[16 17 18 19 20]
  [21 22 23 24 25]
  [26 27 28 29 30]]

 [[31 32 33 34 35]
  [36 37 38 39 40]
  [41 42 43 44 45]]

 [[46 47 48 49 50]
  [51 52 53 54 55]
  [56 57 58 59 60]]]

10.1 Complex sub-arrays:
arr_3d[1:3, 1:, 2:4] - Matrices 1-2, Rows 1-2, Columns 2-3:
[[[23 24]
  [28 29]]

 [[38 39]
  [43 44]]]

arr_3d[:2, :2, :3] - Top-left-front cube:
[[[ 1  2  3]
  [ 6  7  8]]

 [[16 17 18]
  [21 22 23]]]

10.2 With steps in all dimensions:
arr_3d[::2, ::2, ::2] - Every 2nd element in all dimensions:
[[[ 1  3  5]
  [11 13 15]]

 [[31 33 35]
  [41 43 45]]]

arr_3d[::-1, ::-1, ::-1] - Complete 3D reverse:
[[[60 59 58 57 56]
  [55 54 53 52 51]
  [50 49 48 47 46]]

 [[45 44 43 42 41]
  [40 39 38 37 36]
  [35 34 33 32 31]]

 [[30 29 28 27 26]
  [25 24 23 22 21]
  [20 19 18 17 16]]

 [[15 14 13 12 11]
  [10  9  8  7  6]
  [ 5  4  3  2  1]]]


In [19]:
# 11. ADVANCED 3D INDEXING


print("\n11.1 Boolean indexing:")
print("arr_3d > 30 - Elements greater than 30:")
print(arr_3d[arr_3d > 30])

print("\n11.2 Fancy indexing:")
print("arr_3d[[0, 2]] - Matrices 0 and 2:")
print(arr_3d[[0, 2]])

print("\narr_3d[[0, 1], [0, 2]] - Specific matrix-row combinations:")
print(arr_3d[[0, 1], [0, 2]])


11.1 Boolean indexing:
arr_3d > 30 - Elements greater than 30:
[31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54
 55 56 57 58 59 60]

11.2 Fancy indexing:
arr_3d[[0, 2]] - Matrices 0 and 2:
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]

 [[31 32 33 34 35]
  [36 37 38 39 40]
  [41 42 43 44 45]]]

arr_3d[[0, 1], [0, 2]] - Specific matrix-row combinations:
[[ 1  2  3  4  5]
 [26 27 28 29 30]]


In [22]:
#  PRACTICAL EXERCISES


square_arr = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

print("\nSquare Array:")
print(square_arr)
print("\nMain diagonal:")
print(np.diag(square_arr))
print("\nAnti-diagonal:")
print(np.diag(np.fliplr(square_arr)))

print("\n" + "-" * 80)
print("Exercise 2: Extract corners from 2D array")
print("-" * 80)

print("\nTop-left 2x2:")
print(arr_2d[:2, :2])
print("\nTop-right 2x2:")
print(arr_2d[:2, -2:])
print("\nBottom-left 2x2:")
print(arr_2d[-2:, :2])
print("\nBottom-right 2x2:")
print(arr_2d[-2:, -2:])

print("\n" + "-" * 80)
print("Exercise 3: Checkerboard pattern from 2D array")
print("-" * 80)

print("\nWhite squares (even rows, even columns):")
print(arr_2d[::2, ::2])
print("\nBlack squares (odd rows, odd columns):")
print(arr_2d[1::2, 1::2])

print("\n" + "-" * 80)
print("Exercise 4: Extract specific planes from 3D array")
print("-" * 80)

print("\nFront face (first matrix):")
print(arr_3d[0, :, :])
print("\nTop face (first row from all matrices):")
print(arr_3d[:, 0, :])
print("\nRight face (last column from all matrices):")
print(arr_3d[:, :, -1])

print("\n" + "-" * 80)
print("Exercise 5: Conditional slicing")
print("-" * 80)

print("\nRows where first element > 10:")
mask = arr_2d[:, 0] > 10
print(arr_2d[mask])

print("\nElements in 3D array divisible by 5:")
print(arr_3d[arr_3d % 5 == 0])

# SUMMARY TABLE


summary = """
╔════════════════════════════════════════════════════════════════════════════╗
║                        INDEXING & SLICING CHEAT SHEET                      ║
╠════════════════════════════════════════════════════════════════════════════╣
║ OPERATION                    │ 2D SYNTAX           │ 3D SYNTAX             ║
╠══════════════════════════════╪═════════════════════╪═══════════════════════╣
║ Single element               │ arr[i, j]           │ arr[i, j, k]          ║
║ Entire row                   │ arr[i]              │ arr[i, j]             ║
║ Entire column                │ arr[:, j]           │ arr[:, :, k]          ║
║ Multiple rows                │ arr[i:j]            │ arr[i:j, :, :]        ║
║ Multiple columns             │ arr[:, i:j]         │ arr[:, :, i:j]        ║
║ Sub-array                    │ arr[i1:i2, j1:j2]   │ arr[i1:i2, j1:j2, k1:k2]
║ Every nth element            │ arr[::n, ::n]       │ arr[::n, ::n, ::n]    ║
║ Reverse                      │ arr[::-1, ::-1]     │ arr[::-1, ::-1, ::-1] ║
║ Boolean indexing             │ arr[arr > val]      │ arr[arr > val]        ║
║ Fancy indexing               │ arr[[i1, i2], [j1, j2]]  │ Similar pattern   ║
╚══════════════════════════════╧═════════════════════╧═══════════════════════╝

KEY CONCEPTS:
• [start:stop:step] - Standard slicing syntax
• Negative indices count from the end: -1 is last element
• Omitting start defaults to 0, omitting stop defaults to end
• Step can be negative for reversing
• Boolean masks filter elements based on conditions
• Fancy indexing uses lists/arrays of indices
"""



Square Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Main diagonal:
[ 1  6 11 16]

Anti-diagonal:
[ 4  7 10 13]

--------------------------------------------------------------------------------
Exercise 2: Extract corners from 2D array
--------------------------------------------------------------------------------

Top-left 2x2:
[[1 2]
 [7 8]]

Top-right 2x2:
[[ 5  6]
 [11 12]]

Bottom-left 2x2:
[[13 14]
 [19 20]]

Bottom-right 2x2:
[[17 18]
 [23 24]]

--------------------------------------------------------------------------------
Exercise 3: Checkerboard pattern from 2D array
--------------------------------------------------------------------------------

White squares (even rows, even columns):
[[ 1  3  5]
 [13 15 17]]

Black squares (odd rows, odd columns):
[[ 8 10 12]
 [20 22 24]]

--------------------------------------------------------------------------------
Exercise 4: Extract specific planes from 3D array
---------------------------------------------