In [3]:
import numpy as np

# 1️⃣ permutation()
arr1 = np.array([1, 2, 3, 4, 5])
perm = np.random.permutation(arr1)
# print("1️⃣ permutation() - Random permutation of array:")
print("Original:", arr1)
print("Permutation:", perm, "\n")

# 2️⃣ shuffle()
arr2 = np.array([10, 20, 30, 40, 50])
np.random.shuffle(arr2)
# print("2️⃣ shuffle() - Shuffle array in-place:")
print("Shuffled:", arr2, "\n")

# 3️⃣ uniform()
uniform_arr = np.random.uniform(low=0.0, high=10.0, size=(3, 3))
# print("3️⃣ uniform() - Uniform distribution [0,10):")
print(uniform_arr, "\n")

# 4️⃣ integers()
int_arr = np.random.randint(low=0, high=100, size=(3, 3))
# print("4️⃣ integers() - Random integers from 0–99:")
print(int_arr, "\n")

# 5️⃣ standard_normal()
stdnorm_arr = np.random.standard_normal(size=(3, 3))
# print("5️⃣ standard_normal() - Normal distribution (mean=0, std=1):")
print(stdnorm_arr, "\n")

# 6️⃣ binomial()
binom_arr = np.random.binomial(n=10, p=0.5, size=5)
# print("6️⃣ binomial() - Binomial distribution (n=10, p=0.5):")
print(binom_arr, "\n")

# 7️⃣ normal()
normal_arr = np.random.normal(loc=50, scale=10, size=(3, 3))
# print("7️⃣ normal() - Gaussian distribution (mean=50, std=10):")
print(normal_arr, "\n")

# 8️⃣ beta()
beta_arr = np.random.beta(a=2.0, b=5.0, size=5)
# print("8️⃣ beta() - Beta distribution (a=2, b=5):")
print(beta_arr, "\n")

# 9️⃣ chisquare()
chi_arr = np.random.chisquare(df=2, size=5)
# print("9️⃣ chisquare() - Chi-square distribution (df=2):")
print(chi_arr, "\n")

# 🔟 gamma()
gamma_arr = np.random.gamma(shape=2.0, scale=1.0, size=5)
# print("🔟 gamma() - Gamma distribution (shape=2, scale=1):")
print(gamma_arr, "\n")

# BONUS: uniform() [0, 1)
uni_default = np.random.uniform(size=(3, 3))
# print("🔹 BONUS uniform() - Uniform [0,1) default:")
print(uni_default, "\n")


Original: [1 2 3 4 5]
Permutation: [1 4 3 5 2] 

Shuffled: [50 10 30 20 40] 

[[2.58958022 6.46023715 9.47094767]
 [6.13507964 7.14646436 9.87081393]
 [7.50810676 3.61115764 1.63218737]] 

[[82 12  6]
 [18  3 80]
 [87 12 67]] 

[[ 0.52177309 -0.86739618  1.36189129]
 [-0.60890551  0.70147505  0.23397566]
 [ 1.05038635  0.67685102  0.49773688]] 

[6 3 7 4 3] 

[[62.10834216 41.95512234 48.86113478]
 [66.90599218 54.26210395 42.33797977]
 [68.46189385 36.97737799 40.97431238]] 

[0.54715657 0.70415312 0.25080281 0.27000161 0.18900419] 

[1.91611206 0.16985222 5.39923438 2.01849868 1.81417495] 

[1.65968155 0.93255159 3.89002807 0.54355269 0.78593581] 

[[0.80626026 0.93647458 0.14469876]
 [0.26154789 0.14236269 0.60787771]
 [0.27593326 0.06759516 0.22412668]] 



In [2]:
pip install numpy

   ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
    --------------------------------------- 0.3/12.8 MB ? eta -:--:--
    --------------------------------------- 0.3/12.8 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.8 MB 834.6 kB/s eta 0:00:15
   --- ------------------------------------ 1.0/12.8 MB 1.3 MB/s eta 0:00:10
   ---- ----------------------------------- 1.6/12.8 MB 1.6 MB/s eta 0:00:07
   ------ --------------------------------- 2.1/12.8 MB 1.8 MB/s eta 0:00:06
   -------- ------------------------------- 2.6/12.8 MB 1.9 MB/s eta 0:00:06
   --------- ------------------------------ 2.9/12.8 MB 1.8 MB/s eta 0:00:06
   --------- ------------------------------ 3.1/12.8 MB 1.8 MB/s eta 0:00:06
   ----------- ---------------------------- 3.7/12.8 MB 1.8 MB/s eta 0:00:06
   ----------- ---------------------------- 3.7/12.8 MB 1.8 MB/s eta 0:00:06
   ------------- -------------------------- 4.2/12.8 MB 1.7 MB/s eta 0:00:06
   ---------------

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 25.1.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
import numpy as np

# Base array
arr = np.array([-3.5, -0.2, 0, 2.3, 5.7])
arr2 = np.array([2, 4, 0.5, -1, -3])

print("Original Array:\n", arr)
print("Second Array:\n", arr2)
print("="*70)

# -------------------- Unary Universal Functions --------------------

# print("\n🔹 abs / fabs:")
print(np.abs(arr))
print(np.fabs(arr))   # fabs only works on real numbers

# print("\n🔹 sqrt (square root):")
print(np.sqrt(np.abs(arr)))   # abs to avoid sqrt of negatives

# print("\n🔹 square (x²):")
print(np.square(arr))

# print("\n🔹 exp (e^x):")
print(np.exp(arr))

# print("\n🔹 log / log10 / log2 / log1p:")
pos = np.abs(arr) + 1e-3  # avoid log(0)
print("log:", np.log(pos))
print("log10:", np.log10(pos))
print("log2:", np.log2(pos))
print("log1p:", np.log1p(pos))

# print("\n🔹 sign (1, 0, -1):")
print(np.sign(arr))

# print("\n🔹 ceil:")
print(np.ceil(arr))

# print("\n🔹 floor:")
print(np.floor(arr))

# print("\n🔹 rint (round to nearest int):")
print(np.rint(arr))

# print("\n🔹 modf (fractional, integral parts):")
frac, integ = np.modf(arr)
print("Fractional:", frac)
print("Integral:", integ)

# print("\n🔹 isnan (is NaN):")
nan_arr = np.array([1, np.nan, np.inf, -np.inf])
print(np.isnan(nan_arr))

# print("\n🔹 isfinite / isinf:")
print("isfinite:", np.isfinite(nan_arr))
print("isinf:", np.isinf(nan_arr))

# print("\n🔹 Trigonometric functions (cos, sin, tan):")
print("cos:", np.cos(arr))
print("sin:", np.sin(arr))
print("tan:", np.tan(arr))

# print("\n🔹 Hyperbolic trig functions (cosh, sinh, tanh):")
print("cosh:", np.cosh(arr))
print("sinh:", np.sinh(arr))
print("tanh:", np.tanh(arr))

#   print("\n🔹 Inverse trig functions (arccos, arcsin, arctan):")
limited = np.clip(arr / 6, -1, 1)   # keep within valid domain [-1,1]
print("arccos:", np.arccos(limited))
print("arcsin:", np.arcsin(limited))
print("arctan:", np.arctan(limited))

#   print("\n🔹 Inverse hyperbolic trig functions (arccosh, arcsinh, arctanh):")
pos_vals = np.abs(arr) + 1
frac_vals = np.clip(arr / 6, -0.9, 0.9)
print("arccosh:", np.arccosh(pos_vals))
print("arcsinh:", np.arcsinh(arr))
print("arctanh:", np.arctanh(frac_vals))

# print("\n🔹 logical_not (NOT):")
bool_arr = np.array([True, False, True, False])
print(np.logical_not(bool_arr))

print("="*70)
# -------------------- Binary Universal Functions --------------------

# print("\n🔹 add:")
print(np.add(arr, arr2))

# print("\n🔹 subtract:")
print(np.subtract(arr, arr2))

# print("\n🔹 multiply:")
print(np.multiply(arr, arr2))

# print("\n🔹 divide:")
print(np.divide(arr, arr2))

# print("\n🔹 floor_divide:")
print(np.floor_divide(arr, arr2))

# print("\n🔹 power (x^y):")
print(np.power(arr, 2))

# print("\n🔹 maximum / fmax:")
nan_mix = np.array([np.nan, 2, 5])
print("maximum:", np.maximum(nan_mix, 3))
print("fmax:", np.fmax(nan_mix, 3))   # ignores NaN

# print("\n🔹 minimum / fmin:")
print("minimum:", np.minimum(nan_mix, 3))
# print("\n🔹 mod (remainder):")
print(np.mod(arr, arr2))

# print("\n🔹 copysign (copy sign of arr2 to arr):")
print(np.copysign(arr, arr2))

# print("\n🔹 Comparison operators (greater, less_equal, equal, not_equal):")
print("greater:", np.greater(arr, arr2))
print("greater_equal:", np.greater_equal(arr, arr2))
print("less:", np.less(arr, arr2))
print("less_equal:", np.less_equal(arr, arr2))
print("equal:", np.equal(arr, arr2))
print("not_equal:", np.not_equal(arr, arr2))

# print("\n🔹 logical operations (and, or, xor):")
bool1 = np.array([True, False, True])
bool2 = np.array([False, False, True])
print("logical_and:", np.logical_and(bool1, bool2))
print("logical_or:", np.logical_or(bool1, bool2))
print("logical_xor:", np.logical_xor(bool1, bool2))


Original Array:
 [-3.5 -0.2  0.   2.3  5.7]
Second Array:
 [ 2.   4.   0.5 -1.  -3. ]
[3.5 0.2 0.  2.3 5.7]
[3.5 0.2 0.  2.3 5.7]
[1.87082869 0.4472136  0.         1.51657509 2.38746728]
[12.25  0.04  0.    5.29 32.49]
[3.01973834e-02 8.18730753e-01 1.00000000e+00 9.97418245e+00
 2.98867401e+02]
log: [ 1.25304864 -1.60445037 -6.90775528  0.83334381  1.7406416 ]
log10: [ 0.54419211 -0.69680394 -3.          0.36191662  0.75595104]
log2: [ 1.80776706 -2.31473259 -9.96578428  1.20226098  2.511215  ]
log1p: [1.50429959e+00 1.83154543e-01 9.99500333e-04 1.19422545e+00
 1.90225677e+00]
[-1. -1.  0.  1.  1.]
[-3. -0.  0.  3.  6.]
[-4. -1.  0.  2.  5.]
[-4. -0.  0.  2.  6.]
Fractional: [-0.5 -0.2  0.   0.3  0.7]
Integral: [-3. -0.  0.  2.  5.]
[False  True False False]
isfinite: [ True False False False]
isinf: [False False  True  True]
cos: [-0.93645669  0.98006658  1.         -0.66627602  0.83471278]
sin: [ 0.35078323 -0.19866933  0.          0.74570521 -0.55068554]
tan: [-0.37458564 -0.20271